#!/usr/bin/env python3
"""
Create a collage PNG from top-view images generated by outcar_relax_to_ovito_real.py.

For each calculation directory found recursively, the script:
- finds a top-view image (*_view_xy.png)
- reads the final total energy from OSZICAR or OUTCAR
- computes adsorption energy: E_ads = E_final - E_reference
- creates a tiled montage with 5 columns by default
- writes a CSV summary with directory, image, energy source, E_final, and E_ads

Typical use:
    python make_adsorption_montage.py . --reference -1234.56789

Natural sort is the default, so folders like 1, 2, ..., 10 are ordered correctly.
You can also sort by adsorption energy from most negative to most positive:
    python make_adsorption_montage.py . --reference -1234.56789 --sort energy
"""

from __future__ import annotations

import argparse
import csv
import fnmatch
import math
import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional, Sequence, Tuple

from PIL import Image, ImageDraw, ImageFont, ImageOps


OSZICAR_E0_RE = re.compile(r"E0=\s*([+-]?(?:\d+\.\d*|\d*\.\d+|\d+)(?:[Ee][+-]?\d+)?)")
OSZICAR_F_RE = re.compile(r"F=\s*([+-]?(?:\d+\.\d*|\d*\.\d+|\d+)(?:[Ee][+-]?\d+)?)")
OUTCAR_TOTEN_RE = re.compile(r"free\s+energy\s+TOTEN\s*=\s*([+-]?(?:\d+\.\d*|\d*\.\d+|\d+)(?:[Ee][+-]?\d+)?)\s+eV")
OUTCAR_SIGMA_RE = re.compile(r"energy\s+without\s+entropy=\s*([+-]?(?:\d+\.\d*|\d*\.\d+|\d+)(?:[Ee][+-]?\d+)?)")
NATURAL_TOKEN_RE = re.compile(r"(\d+)")


@dataclass
class Entry:
    calc_dir: Path
    label: str
    image_path: Path
    source_file: Path
    source_kind: str
    e_final: float
    e_ads: float


# ------- Energy parsing -------
def parse_last_energy_from_oszicar(path: Path) -> Optional[float]:
    last_e0 = None
    last_f = None
    with path.open("r", errors="ignore") as fh:
        for line in fh:
            m = OSZICAR_E0_RE.search(line)
            if m:
                last_e0 = float(m.group(1))
            m = OSZICAR_F_RE.search(line)
            if m:
                last_f = float(m.group(1))
    return last_e0 if last_e0 is not None else last_f


def parse_last_energy_from_outcar(path: Path) -> Optional[float]:
    last_toten = None
    last_sigma = None
    with path.open("r", errors="ignore") as fh:
        for line in fh:
            m = OUTCAR_TOTEN_RE.search(line)
            if m:
                last_toten = float(m.group(1))
            m = OUTCAR_SIGMA_RE.search(line)
            if m:
                last_sigma = float(m.group(1))
    return last_toten if last_toten is not None else last_sigma


def get_final_energy(calc_dir: Path) -> Tuple[float, Path, str]:
    osz = calc_dir / "OSZICAR"
    out = calc_dir / "OUTCAR"

    if osz.is_file():
        e = parse_last_energy_from_oszicar(osz)
        if e is not None:
            return e, osz, "OSZICAR"

    if out.is_file():
        e = parse_last_energy_from_outcar(out)
        if e is not None:
            return e, out, "OUTCAR"

    raise RuntimeError(f"Could not determine final energy from OSZICAR or OUTCAR in: {calc_dir}")


# ------- Sorting -------
def natural_key(text: str):
    parts = NATURAL_TOKEN_RE.split(text)
    key = []
    for part in parts:
        if not part:
            continue
        if part.isdigit():
            key.append(int(part))
        else:
            key.append(part.lower())
    return tuple(key)


def sort_entries(entries: List[Entry], mode: str) -> List[Entry]:
    if mode == "energy":
        return sorted(entries, key=lambda e: (e.e_ads, natural_key(e.label)))
    return sorted(entries, key=lambda e: natural_key(e.label))


# ------- Image discovery -------
def choose_xy_image(calc_dir: Path, explicit_name: Optional[str] = None) -> Optional[Path]:
    if explicit_name:
        p = calc_dir / explicit_name
        return p if p.is_file() else None

    preferred = calc_dir / "relax_view_xy.png"
    if preferred.is_file():
        return preferred

    candidates = sorted(calc_dir.glob("*_view_xy.png"), key=lambda p: p.stat().st_mtime)
    if not candidates:
        return None
    return candidates[-1]


# ------- Filtering -------
def _norm_values(values: Optional[Sequence[str]]) -> List[str]:
    out: List[str] = []
    for v in values or []:
        vv = str(v).strip()
        if vv:
            out.append(vv)
    return out


def _match_any_prefix(parts: Sequence[str], prefixes: Sequence[str]) -> bool:
    return any(part.startswith(pref) for part in parts for pref in prefixes)


def _match_only_token(rel_path: str, parts: Sequence[str], tokens: Sequence[str]) -> bool:
    for tok in tokens:
        if rel_path == tok:
            return True
        if rel_path.startswith(tok.rstrip("/") + "/"):
            return True
        if parts and parts[-1] == tok:
            return True
    return False


def _match_any_glob(rel_path: str, basename: str, patterns: Sequence[str]) -> bool:
    for pat in patterns:
        if fnmatch.fnmatch(rel_path, pat) or fnmatch.fnmatch(basename, pat):
            return True
    return False


def should_keep_dir(
    calc_dir: Path,
    root: Path,
    include_prefixes: Sequence[str],
    exclude_prefixes: Sequence[str],
    only_tokens: Sequence[str],
    include_globs: Sequence[str],
    exclude_globs: Sequence[str],
) -> bool:
    rel = calc_dir.relative_to(root)
    rel_str = rel.as_posix()
    parts = rel.parts
    basename = calc_dir.name

    if exclude_prefixes and _match_any_prefix(parts, exclude_prefixes):
        return False
    if exclude_globs and _match_any_glob(rel_str, basename, exclude_globs):
        return False

    if only_tokens and not _match_only_token(rel_str, parts, only_tokens):
        return False
    if include_prefixes and not _match_any_prefix(parts, include_prefixes):
        return False
    if include_globs and not _match_any_glob(rel_str, basename, include_globs):
        return False

    return True


# ------- Text/font helpers -------
def load_font(size: int) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    candidates = [
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf",
        "/usr/share/fonts/truetype/freefont/FreeSans.ttf",
    ]
    for fp in candidates:
        if os.path.exists(fp):
            try:
                return ImageFont.truetype(fp, size=size)
            except Exception:
                pass
    return ImageFont.load_default()


def fit_font(draw: ImageDraw.ImageDraw, text: str, max_width: int, start_size: int, min_size: int = 12):
    for size in range(start_size, min_size - 1, -1):
        font = load_font(size)
        bbox = draw.textbbox((0, 0), text, font=font)
        if (bbox[2] - bbox[0]) <= max_width:
            return font
    return load_font(min_size)


# ------- Montage creation -------
def create_tile(entry: Entry, tile_width: int, image_height: int, top_h: int, bottom_h: int, label_size: int, energy_size: int) -> Image.Image:
    tile_height = top_h + image_height + bottom_h
    tile = Image.new("RGB", (tile_width, tile_height), "white")
    draw = ImageDraw.Draw(tile)

    label_font = fit_font(draw, entry.label, tile_width - 16, label_size)
    e_text = f"Eads = {entry.e_ads:.3f} eV"
    energy_font = fit_font(draw, e_text, tile_width - 16, energy_size)

    bbox = draw.textbbox((0, 0), entry.label, font=label_font)
    tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
    draw.text(((tile_width - tw) / 2, (top_h - th) / 2 - 2), entry.label, fill="black", font=label_font)

    im = Image.open(entry.image_path).convert("RGB")
    contained = ImageOps.contain(im, (tile_width - 16, image_height - 10), method=Image.Resampling.LANCZOS)
    x = (tile_width - contained.width) // 2
    y = top_h + (image_height - contained.height) // 2
    tile.paste(contained, (x, y))

    bbox = draw.textbbox((0, 0), e_text, font=energy_font)
    tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
    draw.text(((tile_width - tw) / 2, top_h + image_height + (bottom_h - th) / 2 - 2), e_text, fill="black", font=energy_font)

    return tile


def make_montage(entries: List[Entry], output_png: Path, columns: int, tile_width: int, image_height: int, top_h: int, bottom_h: int, margin: int, gutter: int, label_size: int, energy_size: int):
    if not entries:
        raise RuntimeError("No entries to draw in montage.")

    rows = math.ceil(len(entries) / columns)
    tile_height = top_h + image_height + bottom_h
    canvas_w = margin * 2 + columns * tile_width + (columns - 1) * gutter
    canvas_h = margin * 2 + rows * tile_height + (rows - 1) * gutter

    canvas = Image.new("RGB", (canvas_w, canvas_h), "white")

    for idx, entry in enumerate(entries):
        r = idx // columns
        c = idx % columns
        x = margin + c * (tile_width + gutter)
        y = margin + r * (tile_height + gutter)
        tile = create_tile(entry, tile_width, image_height, top_h, bottom_h, label_size, energy_size)
        canvas.paste(tile, (x, y))

    output_png.parent.mkdir(parents=True, exist_ok=True)
    canvas.save(output_png)


# ------- Discovery -------
def build_entries(
    root: Path,
    reference_energy: float,
    image_name: Optional[str],
    label_mode: str,
    include_prefixes: Sequence[str],
    exclude_prefixes: Sequence[str],
    only_tokens: Sequence[str],
    include_globs: Sequence[str],
    exclude_globs: Sequence[str],
    sort_mode: str,
) -> List[Entry]:
    entries: List[Entry] = []

    for calc_dir in sorted((p for p in root.rglob("*") if p.is_dir()), key=lambda p: str(p)):
        if not should_keep_dir(
            calc_dir=calc_dir,
            root=root,
            include_prefixes=include_prefixes,
            exclude_prefixes=exclude_prefixes,
            only_tokens=only_tokens,
            include_globs=include_globs,
            exclude_globs=exclude_globs,
        ):
            continue

        image_path = choose_xy_image(calc_dir, explicit_name=image_name)
        if image_path is None:
            continue
        if not ((calc_dir / "OUTCAR").is_file() or (calc_dir / "OSZICAR").is_file()):
            continue

        try:
            e_final, source_file, source_kind = get_final_energy(calc_dir)
        except Exception:
            continue

        if label_mode == "basename":
            label = calc_dir.name
        else:
            label = str(calc_dir.relative_to(root))

        entries.append(
            Entry(
                calc_dir=calc_dir,
                label=label,
                image_path=image_path,
                source_file=source_file,
                source_kind=source_kind,
                e_final=e_final,
                e_ads=e_final - reference_energy,
            )
        )

    return sort_entries(entries, sort_mode)


def write_csv(entries: List[Entry], csv_path: Path):
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    with csv_path.open("w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(["label", "calc_dir", "image_path", "energy_source", "energy_source_file", "E_final_eV", "E_ads_eV"])
        for e in entries:
            w.writerow([e.label, str(e.calc_dir), str(e.image_path), e.source_kind, str(e.source_file), f"{e.e_final:.8f}", f"{e.e_ads:.8f}"])


# ------- CLI -------
def parse_args():
    p = argparse.ArgumentParser(description="Create a collage of top-view PNGs and adsorption energies from recursive OUTCAR/OSZICAR search.")
    p.add_argument("root", help="Root directory to search recursively.")
    p.add_argument("--reference", type=float, required=True, help="Reference energy in eV. The script computes Eads = E_final - E_reference.")
    p.add_argument("-o", "--output", default="adsorption_montage.png", help="Output montage PNG path. Default: adsorption_montage.png")
    p.add_argument("--csv", default="adsorption_montage.csv", help="Output CSV summary path. Default: adsorption_montage.csv")
    p.add_argument("--columns", type=int, default=5, help="Number of columns in the montage. Default: 5")
    p.add_argument("--image-name", default=None, help="Exact top-view image name to use in each directory. If omitted, the script prefers relax_view_xy.png and otherwise the newest *_view_xy.png")
    p.add_argument("--label-mode", choices=["relative", "basename"], default="relative", help="Use relative path from root or only the leaf directory name as label. Default: relative")
    p.add_argument("--sort", choices=["natural", "energy"], default="natural", help="Sort panels by natural path order or by adsorption energy. 'energy' sorts from most negative Eads to most positive. Default: natural")
    p.add_argument("--tile-width", type=int, default=420, help="Width of each panel tile in pixels. Default: 420")
    p.add_argument("--image-height", type=int, default=320, help="Image area height per tile in pixels. Default: 320")
    p.add_argument("--top-height", type=int, default=58, help="Top text area height per tile in pixels. Default: 58")
    p.add_argument("--bottom-height", type=int, default=48, help="Bottom text area height per tile in pixels. Default: 48")
    p.add_argument("--margin", type=int, default=24, help="Outer canvas margin in pixels. Default: 24")
    p.add_argument("--gutter", type=int, default=20, help="Gap between tiles in pixels. Default: 20")
    p.add_argument("--label-font-size", type=int, default=24, help="Starting font size for the directory label. Default: 24")
    p.add_argument("--energy-font-size", type=int, default=22, help="Starting font size for the energy text. Default: 22")
    p.add_argument("--exclude-prefix", action="append", default=[], help="Exclude any directory whose relative path contains a component starting with this prefix. Repeat option if needed.")
    p.add_argument("--include-prefix", action="append", default=[], help="Keep only directories whose relative path contains a component starting with this prefix. Repeat option if needed.")
    p.add_argument("--only", action="append", default=[], help="Keep only these directories. Match by relative path, path prefix, or basename. Repeat option if needed.")
    p.add_argument("--include-glob", action="append", default=[], help="Keep only directories matching this glob on the relative path or basename, e.g. '6/*' or 'res*'. Repeat option if needed.")
    p.add_argument("--exclude-glob", action="append", default=[], help="Exclude directories matching this glob on the relative path or basename, e.g. 'neb*' or '*/scratch/*'. Repeat option if needed.")
    return p.parse_args()


def main():
    args = parse_args()
    root = Path(args.root).expanduser().resolve()
    if not root.is_dir():
        raise RuntimeError(f"Root must be a directory: {root}")

    output_png = Path(args.output).expanduser()
    if not output_png.is_absolute():
        output_png = root / output_png

    output_csv = Path(args.csv).expanduser()
    if not output_csv.is_absolute():
        output_csv = root / output_csv

    include_prefixes = _norm_values(args.include_prefix)
    exclude_prefixes = _norm_values(args.exclude_prefix)
    only_tokens = _norm_values(args.only)
    include_globs = _norm_values(args.include_glob)
    exclude_globs = _norm_values(args.exclude_glob)

    entries = build_entries(
        root=root,
        reference_energy=args.reference,
        image_name=args.image_name,
        label_mode=args.label_mode,
        include_prefixes=include_prefixes,
        exclude_prefixes=exclude_prefixes,
        only_tokens=only_tokens,
        include_globs=include_globs,
        exclude_globs=exclude_globs,
        sort_mode=args.sort,
    )
    if not entries:
        raise RuntimeError(
            "No matching calculation directories were found. Check your root path and include/exclude filters. "
            "Expected directories containing OUTCAR or OSZICAR and a top-view image such as relax_view_xy.png"
        )

    make_montage(
        entries=entries,
        output_png=output_png,
        columns=args.columns,
        tile_width=args.tile_width,
        image_height=args.image_height,
        top_h=args.top_height,
        bottom_h=args.bottom_height,
        margin=args.margin,
        gutter=args.gutter,
        label_size=args.label_font_size,
        energy_size=args.energy_font_size,
    )
    write_csv(entries, output_csv)

    print(f"Root directory        : {root}")
    print(f"Entries in montage    : {len(entries)}")
    print(f"Reference energy (eV) : {args.reference:.8f}")
    print(f"Sort mode             : {args.sort}")
    if include_prefixes:
        print(f"Include prefixes      : {', '.join(include_prefixes)}")
    if exclude_prefixes:
        print(f"Exclude prefixes      : {', '.join(exclude_prefixes)}")
    if only_tokens:
        print(f"Only                  : {', '.join(only_tokens)}")
    if include_globs:
        print(f"Include globs         : {', '.join(include_globs)}")
    if exclude_globs:
        print(f"Exclude globs         : {', '.join(exclude_globs)}")
    print(f"Output PNG            : {output_png}")
    print(f"Output CSV            : {output_csv}")


if __name__ == "__main__":
    main()
